version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10.0.0
    working_directory: ~/mini-xmind

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/mini-xmind

jobs:
  setup:
    <<: *container_config
    steps:
      - checkout
      - run: node -v
      - run: npm -v
      - run: npm install
      - run:
          command: |
            set +eo
            npm ls
            true
      - persist_to_workspace:
          root: ~/mini-xmind
          paths:
            - node_modules
  lint:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run lint
  test:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run codecov
      - run: bash <(curl -s https://codecov.io/bash) -t 31625cdc-8c32-47d0-a303-baf981cab0f5
  compile:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run compile
      - run: ls -l lib
      - run: ls -l lib/tools
      - run: node ./scripts/dekko-lib.js
      - persist_to_workspace:
          root: ~/mini-xmind
          paths:
            - lib
  test_lib:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          command: npm test -- -u --maxWorkers=2
          environment:
            LIB_DIR: lib

workflows:
  version: 2
  build:
    jobs:
      - setup:
          filters:
            branches:
              ignore: gh-pages
      - compile:
          requires:
            - setup
      - test_lib:
          requires:
            - compile
      - test:
          requires:
            - setup
      - lint:
          requires:
            - setup
