name: test-es

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install

      - name: compile
        run: npm run compile

      - name: test esm
        run: npm run test:es
